import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Abhiram",
  description: "Generated by create next app",
  icons:{
    icon:"/icon.jpg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cx = (...classes) => classes.filter(Boolean).join(" ");

  return (
    <html lang="en" className={cx(GeistSans.variable, GeistMono.variable)}>
    
      <body
        className={` antialiased max-w-2xl mb-40 flex flex-col md:flex-row mx-4 mt-4 lg:mx-auto`}
      >
        <main className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0">
          <Nav />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
